//let query = `INSERT INTO [dbo].[depth_data60] (
//          [Symbol]
//         ,[Market]
//         ,[EventTime]
//         ,[avgSellVol1]
//         ,[avgSellVol2]
//         ,[avgSellVol3]
//         ,[avgSellVol4]
//         ,[avgSellVol5]
//         ,[predictedSellVol10]
//         ,[predictedSellVol60]
//         ,[avgBuyVol1]
//         ,[avgBuyVol2]
//         ,[avgBuyVol3]
//         ,[avgBuyVol4]
//         ,[avgBuyVol5]
//         ,[predictedBuyVol10]
//         ,[predictedBuyVol60]
//         ,[buyClosestPrice]
//         ,[sellClosestPrice]
//         ,[avgSellVol1PriceDepth]
//         ,[avgSellVol1LastVolSize]
//         ,[avgSellVol2PriceDepth]
//         ,[avgSellVol2LastVolSize]
//         ,[avgSellVol3PriceDepth]
//         ,[avgSellVol3LastVolSize]
//         ,[avgSellVol4PriceDepth]
//         ,[avgSellVol4LastVolSize]
//         ,[avgSellVol5PriceDepth]
//         ,[avgSellVol5LastVolSize]
//         ,[predictedSellVol10PriceDepth]
//         ,[predictedSellVol10LastVolSize]
//         ,[predictedSellVol60PriceDepth]
//         ,[predictedSellVol60LastVolSize]
//         ,[avgBuyVol1PriceDepth]
//         ,[avgBuyVol1LastVolSize]
//         ,[avgBuyVol2PriceDepth]
//         ,[avgBuyVol2LastVolSize]
//         ,[avgBuyVol3PriceDepth]
//         ,[avgBuyVol3LastVolSize]
//         ,[avgBuyVol4PriceDepth]
//         ,[avgBuyVol4LastVolSize]
//         ,[avgBuyVol5PriceDepth]
//         ,[avgBuyVol5LastVolSize]
//         ,[predictedBuyVol10PriceDepth]
//         ,[predictedBuyVol10LastVolSize]
//         ,[predictedBuyVol60PriceDepth]
//         ,[predictedBuyVol60LastVolSize]
//         ,[timeToBuy1]
//         ,[timeToBuy05]
//         ,[timeToBuy02]
//         ,[timeToSell1]
//         ,[timeToSell05]
//         ,[timeToSell02]
//         ,[dealsQuantityBuy]
//         ,[dealsQuantitySell]
//         ,[volBuyerMakerInc]
//         ,[volSellerMakerInc]
//         ,[volBuyerMakerDec]
//         ,[volSellerMakerDec]
//         ,[dealsQuantityBuyerMakerInc]
//         ,[dealsQuantitySellerMakerInc]
//         ,[dealsQuantityBuyerMakerDec]
//         ,[dealsQuantitySellerMakerDec]
//         ,[vol02Bids]
//         ,[vol02Asks]
//         ,[vol02BidsPrevPrice]
//         ,[vol02AsksPrevPrice]
//         ,[vol01Bids]
//         ,[vol01Ask]
//         ,[vol01BidsPrevPrice]
//         ,[vol01AsksPrevPrice]
//         ,[vol001Bids]
//         ,[vol001Asks]
//         ,[vol001BidsPrevPrice]
//         ,[vol001AsksPrevPrice]
//         )VALUES(
//           '${param.symbol}',
//           '${param.marketType}',
//            ${eventTime},
//            ${avgSellVol1},
//            ${avgSellVol2},
//            ${avgSellVol3},
//            ${avgSellVol4},
//            ${avgSellVol5},
//            ${predictedSellVol10},
//            ${predictedSellVol60},
//            ${avgBuyVol1},
//            ${avgBuyVol2},
//            ${avgBuyVol3},
//            ${avgBuyVol4},
//            ${avgBuyVol5},
//            ${predictedBuyVol10},
//            ${predictedBuyVol60},
//            ${buyClosestPrice},
//            ${sellClosestPrice},
//            ${avgSellVol1PriceDepth},
//            ${avgSellVol1LastVolSize},
//            ${avgSellVol2PriceDepth},
//            ${avgSellVol2LastVolSize},
//            ${avgSellVol3PriceDepth},
//            ${avgSellVol3LastVolSize},
//            ${avgSellVol4PriceDepth},
//            ${avgSellVol4LastVolSize},
//            ${avgSellVol5PriceDepth},
//            ${avgSellVol5LastVolSize},
//            ${predictedSellVol10PriceDepth},
//            ${predictedSellVol10LastVolSize},
//            ${predictedSellVol60PriceDepth},
//            ${predictedSellVol60LastVolSize},
//            ${avgBuyVol1PriceDepth},
//            ${avgBuyVol1LastVolSize},
//            ${avgBuyVol2PriceDepth},
//            ${avgBuyVol2LastVolSize},
//            ${avgBuyVol3PriceDepth},
//            ${avgBuyVol3LastVolSize},
//            ${avgBuyVol4PriceDepth},
//            ${avgBuyVol4LastVolSize},
//            ${avgBuyVol5PriceDepth},
//            ${avgBuyVol5LastVolSize},
//            ${predictedBuyVol10PriceDepth},
//            ${predictedBuyVol10LastVolSize},
//            ${predictedBuyVol60PriceDepth},
//            ${predictedBuyVol60LastVolSize},
//            ${timeToBuy1},
//            ${timeToBuy05},
//            ${timeToBuy02},
//            ${timeToSell1},
//            ${timeToSell05},
//            ${timeToSell02},
//            ${param.dataBySeconds[1].dealsQuantityBuy},
//            ${param.dataBySeconds[1].dealsQuantitySell},
//            ${param.dataBySeconds[1].volBuyerMakerInc},
//            ${param.dataBySeconds[1].volSellerMakerInc},
//            ${param.dataBySeconds[1].volBuyerMakerDec},
//            ${param.dataBySeconds[1].volSellerMakerDec},
//            ${param.dataBySeconds[1].dealsQuantityBuyerMakerInc},
//            ${param.dataBySeconds[1].dealsQuantitySellerMakerInc},
//            ${param.dataBySeconds[1].dealsQuantityBuyerMakerDec},
//            ${param.dataBySeconds[1].dealsQuantitySellerMakerDec},
//            ${param.dataBySeconds[1].vol02Bids},
//            ${param.dataBySeconds[1].vol02Asks},
//            ${param.dataBySeconds[1].vol02BidsPrevPrice},
//            ${param.dataBySeconds[1].vol02AsksPrevPrice},
//            ${param.dataBySeconds[1].vol01Bids},
//            ${param.dataBySeconds[1].vol01Asks},
//            ${param.dataBySeconds[1].vol01BidsPrevPrice},
//            ${param.dataBySeconds[1].vol01AsksPrevPrice},
//            ${param.dataBySeconds[1].vol001Bids},
//            ${param.dataBySeconds[1].vol001Asks},
//            ${param.dataBySeconds[1].vol001BidsPrevPrice},
//            ${param.dataBySeconds[1].vol001AsksPrevPrice})`;
//   if (param.useSql) {
//     const request = pool.request();
//     request.query(query, (err, result) => {});
//   }
